trigger:
  batch: true
  branches:
    include:
    - master
stages:
  - stage: build
    displayName: Execute Build
    jobs:
      - job: BuildArtifacts
        displayName: Build Project Artifacts
        pool:
          vmImage: windows-latest
        steps:
          - checkout: self
            persistCredentials: true
          - task: UseDotNet@2
            inputs:
              packageType: "sdk"
              version: "3.1.302"
          - task: Cache@2
            displayName: Cache dotnet tools
            inputs:
              key: 'tools | "$(Agent.OS)" | ./.config/dotnet-tools.json'
              path: ".config/"
          - task: Cache@2
            displayName: Cache cake tools
            inputs:
              key: 'cake | "$(Agent.OS)" | ./.config/dotnet-tools.json'
              path: "tools/"
          - task: DotNetCoreCLI@2
            displayName: Restore dotnet tools
            inputs:
              command: "custom"
              custom: "tool"
              arguments: "restore"
          - task: DotNetCoreCLI@2
            displayName: Run GitVersion
            inputs:
              command: "custom"
              custom: "gitversion"
              arguments: "/output buildserver /nofetch"
          - task: DotNetCoreCLI@2
            displayName: Run Cake
            inputs:
              command: "custom"
              custom: "cake"
              arguments: "--verbosity=$(cake.verbosity)"
  - stage: PublishRelease
    displayName: 'Publish to NuGet'
    dependsOn: build
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/head/master'))
    jobs:
    - job: PublishNuGet
      displayName: 'Publish to NuGet'
      pool:
        vmImage: windows-latest
      steps:   
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'specific'
          itemPattern: '**'
          downloadPath: '$(System.ArtifactsDirectory)'
      - task: NuGetCommand@2
        inputs:
          command: 'push'
          packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
          nuGetFeedType: 'external'
          publishFeedCredentials: '$(artifacts.nuget.feed)'